{% set name = "eo-learn-io" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ca357004523308eda2aeaf2a8254384716d4b21c4967148dc2fe9a1d4923ca50

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - eo-learn-core
    - python >=3.5
    - rasterio

test:
  imports:
    - eolearn
    - eolearn.core
    - eolearn.io

about:
  home: https://github.com/sentinel-hub/eo-learn
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A collection of input/output utilities and EOTasks
  doc_url: https://eo-learn.readthedocs.io/en/latest/eolearn.io.html
  dev_url: https://github.com/sentinel-hub/eo-learn

extra:
  recipe-maintainers:
    - mxr-conda
